{{- if .Values.apiService.enabled }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tenancy.kiosk.sh
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ template "kiosk.fullname" . }}-apiservice"
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  version: v1alpha1
  group: tenancy.kiosk.sh
  groupPriorityMinimum: 10000
  service:
    name: {{ template "kiosk.fullname" . }}-apiservice
    namespace: {{ .Release.Namespace }}
  versionPriority: 1000
  caBundle: "Cg=="
{{- end }}
