{{- if .Values.certManager.certificate.create }}
{{- if .Values.apiService.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "kiosk.fullname" . }}-apiservice
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "{{ template "kiosk.fullname" . }}-apiservice.{{ .Release.Namespace }}.svc"
  - "{{ template "kiosk.fullname" . }}-apiservice.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ template "kiosk.fullname" . }}
  secretName: {{ .Values.certSecret }}-apiservice
{{- end }}
{{- end }}
