{{- if .Values.certManager.certificate.create }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "kiosk.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "{{ template "kiosk.fullname" . }}.{{ .Release.Namespace }}.svc"
  - "{{ template "kiosk.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ template "kiosk.fullname" . }}
  secretName: {{ .Values.certSecret }}
{{- end }}
