# permissions to do edit accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-editor-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
