# permissions to do edit accountquotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountquota-editor-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountquotas/status
  verbs:
  - get
  - patch
  - update
