# permissions to do edit accountaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountaccess-editor-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountaccesses/status
  verbs:
  - get
  - patch
  - update
