# permissions to do viewer accountaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountaccess-viewer-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountaccesses/status
  verbs:
  - get
