# permissions to do viewer accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-viewer-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accounts/status
  verbs:
  - get
