# permissions to do viewer accountquotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountquota-viewer-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountquotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - accountquotas/status
  verbs:
  - get
