# permissions to do edit namespaceinitializers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceinitializer-editor-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - namespaceinitializers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - namespaceinitializers/status
  verbs:
  - get
  - patch
  - update
