# permissions to do viewer namespaceinitializers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceinitializer-viewer-role
rules:
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - namespaceinitializers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.kiosk.sh
  resources:
  - namespaceinitializers/status
  verbs:
  - get
